<Project>
  <PropertyGroup>
    <AugaBuildDir>$(MSBuildThisFileDirectory).build\</AugaBuildDir>
    <GameReferenceDir>$(AugaBuildDir)game\</GameReferenceDir>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Auga' Or '$(MSBuildProjectName)' == 'AugaUnityLib'">
    <TargetFramework>netstandard2.1</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
