<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Auga' Or '$(MSBuildProjectName)' == 'AugaUnityLib'">
    <Reference Include="Unity.InputSystem">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="gui_framework">
      <HintPath>$(GameReferenceDir)gui_framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
