"""Generate the optional shim and signature reference from the runtime API. Python 3, no packages."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]

def split_parameters(text):
    parts, start, depth = [], 0, 0
    for i, char in enumerate(text):
        if char in '<[': depth += 1
        elif char in '>]': depth -= 1
        elif char == ',' and depth == 0:
            parts.append(text[start:i].strip())
            start = i + 1
    if text.strip(): parts.append(text[start:].strip())
    return parts

def generate():
    source = (ROOT / 'Auga/API.cs').read_text(encoding='utf-8-sig')
    methods = re.findall(r'public static ([\w<>, .\[\]]+?) (\w+)\(([^)]*)\)', source)
    if not methods: raise RuntimeError('No API signatures found')
    lines = ['// Generated by scripts/api/generate.py. Edit API.cs, then regenerate.',
             'using System;', 'using UnityEngine;', 'using UnityEngine.UI;', '',
             'namespace Auga', '{', '    public static partial class API', '    {']
    reference = ['# Auga API signature reference', '',
                 'Generated from `Auga/API.cs`. See [the integration guide](MODDING.md) for readiness, ownership, and capability limits.', '']
    group = None
    for result, name, parameters in methods:
        result = result.strip()
        parameters = re.sub(r'\[CanBeNull\]\s*', '', parameters)
        parameters = ' '.join(parameters.split())
        current = name.split('_')[0] if '_' in name else 'Core and assets'
        if current != group:
            reference += [f'## {current}', '']
            group = current
        reference += [f'```csharp\n{result} {name}({parameters});\n```', '']
        if name in ('IsLoaded', 'LoadAssembly'): continue
        types, names = [], []
        for parameter in split_parameters(parameters):
            declaration = parameter.split('=')[0].strip()
            type_name, arg_name = declaration.rsplit(' ', 1)
            types.append(f'typeof({type_name})')
            names.append(arg_name)
        args = 'new object[] { ' + ', '.join(names) + ' }'
        signature = 'new Type[] { ' + ', '.join(types) + ' }'
        generic = 'object' if result == 'void' else result
        lines.append(f'        public static {result} {name}({parameters}) => Invoke<{generic}>("{name}", {signature}, {args});')
    lines += ['    }', '}', '']
    return {'Auga/API.External.cs': '\n'.join(lines), 'docs/API-REFERENCE.md': '\n'.join(reference)}

if __name__ == '__main__':
    failed = []
    for path, content in generate().items():
        destination = ROOT / path
        if '--check' in sys.argv:
            if not destination.exists() or destination.read_text(encoding='utf-8-sig') != content:
                failed.append(path)
        else:
            destination.write_text(content, encoding='utf-8')
    if failed:
        raise SystemExit('Regenerate API files: ' + ', '.join(failed))
    print('API generation check passed.' if '--check' in sys.argv else 'Generated API wrapper and reference.')
